export const experienceDict = {
    0: "Chưa có kinh nghiệm",
    1: "Dưới 1 năm",
    2: "1 năm",
    3: "2 năm",
    4: "3 năm",
    5: "4 năm",
    6: "5 năm",
    7: "Trên 5 năm",
    99: "Không yêu cầu"
};

export const getSearchData = (searchData) => {
    let result = {};
    for (const key in searchData) {
        if (typeof(searchData[key]) === "object") {
            if (searchData[key].length !== 0) {
                result[key] = searchData[key];
            }
        } else {
            if (searchData[key] !== "") {
                result[key] = searchData[key];
            }
        }
    }

    return result;
}

const a = {
    "An Giang": "An Giang",
    "an giang": "An Giang",
    "AN GIANG": "An Giang",
    "Việc làm An Giang": "An Giang",
    "Bà Rịa - Vũng Tàu": "Bà Rịa - Vũng Tàu",
    "bà rịa - vũng tàu": "Bà Rịa - Vũng Tàu",
    "BÀ RỊA - VŨNG TÀU": "Bà Rịa - Vũng Tàu",
    "Việc làm Bà Rịa - Vũng Tàu": "Bà Rịa - Vũng Tàu",
    "Bắc Giang": "Bắc Giang",
    "bắc giang": "Bắc Giang",
    "BẮC GIANG": "Bắc Giang",
    "Việc làm Bắc Giang": "Bắc Giang",
    "Bắc Kạn": "Bắc Kạn",
    "bắc kạn": "Bắc Kạn",
    "BẮC KẠN": "Bắc Kạn",
    "Bắc Cạn": "Bắc Kạn",
    "Việc làm Bắc Kạn": "Bắc Kạn",
    "Bạc Liêu": "Bạc Liêu",
    "bạc liêu": "Bạc Liêu",
    "BẠC LIÊU": "Bạc Liêu",
    "Việc làm Bạc Liêu": "Bạc Liêu",
    "Bắc Ninh": "Bắc Ninh",
    "bắc ninh": "Bắc Ninh",
    "BẮC NINH": "Bắc Ninh",
    "Lương Tài": "Bắc Ninh",
    "Việc làm Bắc Ninh": "Bắc Ninh",
    "Bến Tre": "Bến Tre",
    "bến tre": "Bến Tre",
    "BẾN TRE": "Bến Tre",
    "Việc làm Bến Tre": "Bến Tre",
    "Bình Định": "Bình Định",
    "bình định": "Bình Định",
    "BÌNH ĐỊNH": "Bình Định",
    "Việc làm Bình Định": "Bình Định",
    "Bình Dương": "Bình Dương",
    "bình dương": "Bình Dương",
    "BÌNH DƯƠNG": "Bình Dương",
    "Dầu Tiếng": "Bình Dương",
    "Việc làm Bình Dương": "Bình Dương",
    "Bình Phước": "Bình Phước",
    "bình phước": "Bình Phước",
    "BÌNH PHƯỚC": "Bình Phước",
    "Việc làm Bình Phước": "Bình Phước",
    "Bình Thuận": "Bình Thuận",
    "bình thuận": "Bình Thuận",
    "BÌNH THUẬN": "Bình Thuận",
    "Việc làm Bình Thuận": "Bình Thuận",
    "Cà Mau": "Cà Mau",
    "cà mau": "Cà Mau",
    "CÀ MAU": "Cà Mau",
    "Việc làm Cà Mau": "Cà Mau",
    "Cao Bằng": "Cao Bằng",
    "cao bằng": "Cao Bằng",
    "CAO BẰNG": "Cao Bằng",
    "Việc làm Cao Bằng": "Cao Bằng",
    "Đắk Lắk": "Đắk Lắk",
    "đắk lắk": "Đắk Lắk",
    "ĐẮK LẮK": "Đắk Lắk",
    "Việc làm Đắk Lắk": "Đắk Lắk",
    "Dak Lak": "Đắk Lắk",
    "Đắc Lắc": "Đắk Lắk",
    "Đắk Nông": "Đắk Nông",
    "đắk nông": "Đắk Nông",
    "ĐẮK NÔNG": "Đắk Nông",
    "Việc làm Đắk Nông": "Đắk Nông",
    "Dak Nông": "Đắk Nông",
    "Điện Biên": "Điện Biên",
    "điện biên": "Điện Biên",
    "ĐIỆN BIÊN": "Điện Biên",
    "Việc làm Điện Biên": "Điện Biên",
    "Đồng Nai": "Đồng Nai",
    "đồng nai": "Đồng Nai",
    "ĐỒNG NAI": "Đồng Nai",
    "Việc làm Đồng Nai": "Đồng Nai",
    "Đồng Tháp": "Đồng Tháp",
    "đồng tháp": "Đồng Tháp",
    "ĐỒNG THÁP": "Đồng Tháp",
    "Việc làm Đồng Tháp": "Đồng Tháp",
    "Gia Lai": "Gia Lai",
    "gia lai": "Gia Lai",
    "GIA LAI": "Gia Lai",
    "Việc làm Gia Lai": "Gia Lai",
    "Hà Giang": "Hà Giang",
    "hà giang": "Hà Giang",
    "HÀ GIANG": "Hà Giang",
    "Việc làm Hà Giang": "Hà Giang",
    "Hà Nam": "Hà Nam",
    "hà nam": "Hà Nam",
    "HÀ NAM": "Hà Nam",
    "Việc làm Hà Nam": "Hà Nam",
    "Hà Tĩnh": "Hà Tĩnh",
    "hà tĩnh": "Hà Tĩnh",
    "HÀ TĨNH": "Hà Tĩnh",
    "Việc làm Hà Tĩnh": "Hà Tĩnh",
    "Hải Dương": "Hải Dương",
    "hải dương": "Hải Dương",
    "HẢI DƯƠNG": "Hải Dương",
    "Việc làm Hải Dương": "Hải Dương",
    "Hậu Giang": "Hậu Giang",
    "hậu giang": "Hậu Giang",
    "HẬU GIANG": "Hậu Giang",
    "Việc làm Hậu Giang": "Hậu Giang",
    "Hòa Bình": "Hòa Bình",
    "hòa bình": "Hòa Bình",
    "HÒA BÌNH": "Hòa Bình",
    "Hoà Bình": "Hòa Bình",
    "Việc làm Hòa Bình": "Hòa Bình",
    "Hưng Yên": "Hưng Yên",
    "hưng yên": "Hưng Yên",
    "HƯNG YÊN": "Hưng Yên",
    "Việc làm Hưng Yên": "Hưng Yên",
    "Văn Giang": "Hưng Yên",
    "Khánh Hòa": "Khánh Hòa",
    "khánh hòa": "Khánh Hòa",
    "KHÁNH HÒA": "Khánh Hòa",
    "Cam Ranh": "Khánh Hòa",
    "Cam Lâm": "Khánh Hòa",
    "Diên Khánh": "Khánh Hòa",
    "Việc làm Khánh Hòa": "Khánh Hòa",
    "Kiên Giang": "Kiên Giang",
    "kiên giang": "Kiên Giang",
    "KIÊN GIANG": "Kiên Giang",
    "Việc làm Kiên Giang": "Kiên Giang",
    "Kon Tum": "Kon Tum",
    "kon tum": "Kon Tum",
    "KON TUM": "Kon Tum",
    "Việc làm Kon Tum": "Kon Tum",
    "Lai Châu": "Lai Châu",
    "lai châu": "Lai Châu",
    "LAI CHÂU": "Lai Châu",
    "Việc làm Lai Châu": "Lai Châu",
    "Lâm Đồng": "Lâm Đồng",
    "lâm đồng": "Lâm Đồng",
    "LÂM ĐỒNG": "Lâm Đồng",
    "Việc làm Lâm Đồng": "Lâm Đồng",
    "Lạng Sơn": "Lạng Sơn",
    "lạng sơn": "Lạng Sơn",
    "LẠNG SƠN": "Lạng Sơn",
    "Việc làm Lạng Sơn": "Lạng Sơn",
    "Lào Cai": "Lào Cai",
    "lào cai": "Lào Cai",
    "LÀO CAI": "Lào Cai",
    "Việc làm Lào Cai": "Lào Cai",
    "Long An": "Long An",
    "long an": "Long An",
    "LONG AN": "Long An",
    "Việc làm Long An": "Long An",
    "Nam Định": "Nam Định",
    "nam định": "Nam Định",
    "NAM ĐỊNH": "Nam Định",
    "Việc làm Nam Định": "Nam Định",
    "Nghệ An": "Nghệ An",
    "nghệ an": "Nghệ An",
    "NGHỆ AN": "Nghệ An",
    "Việc làm Nghệ An": "Nghệ An",
    "Ninh Bình": "Ninh Bình",
    "ninh bình": "Ninh Bình",
    "NINH BÌNH": "Ninh Bình",
    "Việc làm Ninh Bình": "Ninh Bình",
    "Ninh Thuận": "Ninh Thuận",
    "ninh thuận": "Ninh Thuận",
    "NINH THUẬN": "Ninh Thuận",
    "Việc làm Ninh Thuận": "Ninh Thuận",
    "Phú Thọ": "Phú Thọ",
    "phú thọ": "Phú Thọ",
    "PHÚ THỌ": "Phú Thọ",
    "Việc làm Phú Thọ": "Phú Thọ",
    "Quảng Bình": "Quảng Bình",
    "quảng bình": "Quảng Bình",
    "QUẢNG BÌNH": "Quảng Bình",
    "Việc làm Quảng Bình": "Quảng Bình",
    "Quảng Nam": "Quảng Nam",
    "quảng nam": "Quảng Nam",
    "QUẢNG NAM": "Quảng Nam",
    "Việc làm Quảng Nam": "Quảng Nam",
    "Quảng Ngãi": "Quảng Ngãi",
    "quảng ngãi": "Quảng Ngãi",
    "QUẢNG NGÃI": "Quảng Ngãi",
    "Việc làm Quảng Ngãi": "Quảng Ngãi",
    "Quảng Ninh": "Quảng Ninh",
    "quảng ninh": "Quảng Ninh",
    "QUẢNG NINH": "Quảng Ninh",
    "Việc làm Quảng Ninh": "Quảng Ninh",
    "Quảng Trị": "Quảng Trị",
    "quảng trị": "Quảng Trị",
    "QUẢNG TRỊ": "Quảng Trị",
    "Việc làm Quảng Trị": "Quảng Trị",
    "Sóc Trăng": "Sóc Trăng",
    "sóc trăng": "Sóc Trăng",
    "SÓC TRĂNG": "Sóc Trăng",
    "Việc làm Sóc Trăng": "Sóc Trăng",
    "Sơn La": "Sơn La",
    "sơn la": "Sơn La",
    "SƠN LA": "Sơn La",
    "Việc làm Sơn La": "Sơn La",
    "Tây Ninh": "Tây Ninh",
    "tây ninh": "Tây Ninh",
    "TÂY NINH": "Tây Ninh",
    "Việc làm Tây Ninh": "Tây Ninh",
    "Thái Bình": "Thái Bình",
    "thái bình": "Thái Bình",
    "THÁI BÌNH": "Thái Bình",
    "Việc làm Thái Bình": "Thái Bình",
    "Thái Nguyên": "Thái Nguyên",
    "thái nguyên": "Thái Nguyên",
    "THÁI NGUYÊN": "Thái Nguyên",
    "Việc làm Thái Nguyên": "Thái Nguyên",
    "Thanh Hóa": "Thanh Hóa",
    "thanh hóa": "Thanh Hóa",
    "THANH HÓA": "Thanh Hóa",
    "Việc làm Thanh Hóa": "Thanh Hóa",
    "Thừa Thiên Huế": "Thừa Thiên Huế",
    "thừa thiên huế": "Thừa Thiên Huế",
    "THỪA THIÊN HUẾ": "Thừa Thiên Huế",
    "Việc làm Thừa Thiên Huế": "Thừa Thiên Huế",
    "Thừa Thiên- Huế": "Thừa Thiên Huế",
    "Thừa Thiên Huê": "Thừa Thiên Huế",
    "Tiền Giang": "Tiền Giang",
    "tiền giang": "Tiền Giang",
    "TIỀN GIANG": "Tiền Giang",
    "Việc làm Tiền Giang": "Tiền Giang",
    "Trà Vinh": "Trà Vinh",
    "trà vinh": "Trà Vinh",
    "TRÀ VINH": "Trà Vinh",
    "Việc làm Trà Vinh": "Trà Vinh",
    "Tuyên Quang": "Tuyên Quang",
    "tuyên quang": "Tuyên Quang",
    "TUYÊN QUANG": "Tuyên Quang",
    "Việc làm Tuyên Quang": "Tuyên Quang",
    "Vĩnh Long": "Vĩnh Long",
    "vĩnh long": "Vĩnh Long",
    "VĨNH LONG": "Vĩnh Long",
    "Việc làm Vĩnh Long": "Vĩnh Long",
    "Vĩnh Phúc": "Vĩnh Phúc",
    "vĩnh phúc": "Vĩnh Phúc",
    "VĨNH PHÚC": "Vĩnh Phúc",
    "Việc làm Vĩnh Phúc": "Vĩnh Phúc",
    "Yên Bái": "Yên Bái",
    "yên bái": "Yên Bái",
    "YÊN BÁI": "Yên Bái",
    "Việc làm Yên Bái": "Yên Bái",
    "Phú Yên": "Phú Yên",
    "phú yên": "Phú Yên",
    "PHÚ YÊN": "Phú Yên",
    "Việc làm Phú Yên": "Phú Yên",
    "Cần Thơ": "Cần Thơ",
    "cần thơ": "Cần Thơ",
    "CẦN THƠ": "Cần Thơ",
    "Việc làm Cần Thơ": "Cần Thơ",
    "Đà Nẵng": "Đà Nẵng",
    "đà nẵng": "Đà Nẵng",
    "ĐÀ NẴNG": "Đà Nẵng",
    "Việc làm Đà Nẵng": "Đà Nẵng",
    "Liên Chiểu": "Đà Nẵng",
    "Sơn Trà": "Đà Nẵng",
    "Hải Châu": "Đà Nẵng",
    "Cẩm Lệ": "Đà Nẵng",
    "Thanh Khê": "Đà Nẵng",
    "Hải Phòng": "Hải Phòng",
    "hải phòng": "Hải Phòng",
    "HẢI PHÒNG": "Hải Phòng",
    "Việc làm Hải Phòng": "Hải Phòng",
    "Dương Kinh": "Hải Phòng",
    "Hà Nội": "Hà Nội",
    "hà nội": "Hà Nội",
    "HÀ NỘI": "Hà Nội",
    "Việc làm Hà Nội": "Hà Nội",
    "HN": "Hà Nội",
    "hn": "Hà Nội",
    "Hà Tây": "Hà Nội",
    "Chương Mỹ": "Hà Nội",
    "Long Biên": "Hà Nội",
    "Mỹ Đức": "Hà Nội",
    "Mê Linh": "Hà Nội",
    "Từ Liêm": "Hà Nội",
    "Quốc Oai": "Hà Nội",
    "Phúc Thọ": "Hà Nội",
    "Gia Lâm": "Hà Nội",
    "Thanh Oai": "Hà Nội",
    "Cầu Giấy": "Hà Nội",
    "Hai Bà Trưng": "Hà Nội",
    "Hoàn Kiếm": "Hà Nội",
    "Đan Phượng": "Hà Nội",
    "Thanh Trì": "Hà Nội",
    "Ba Vì": "Hà Nội",
    "Tây Hồ": "Hà Nội",
    "Ba Đình": "Hà Nội",
    "Sơn Tây": "Hà Nội",
    "Đông Anh": "Hà Nội",
    "Ứng Hoà": "Hà Nội",
    "Sóc Sơn": "Hà Nội",
    "Thạch Thất": "Hà Nội",
    "Thanh Xuân": "Hà Nội",
    "Hoàng Mai": "Hà Nội",
    "Hoài Đức": "Hà Nội",
    "Đống Đa": "Hà Nội",
    "Bình Chánh": "Hồ Chí Minh",
    "Thường Tín": "Hà Nội",
    "Tân Bình": "Hồ Chí Minh",
    "Bình Thạnh": "Hồ Chí Minh",
    "Củ Chi": "Hồ Chí Minh",
    "Phú Nhuận": "Hồ Chí Minh",
    "Thủ Đức": "Hồ Chí Minh",
    "Gò Vấp": "Hồ Chí Minh",
    "Bình Tân": "Hồ Chí Minh",
    "Tân Phú": "Hồ Chí Minh",
    "Hóc Môn": "Hồ Chí Minh",
    "Nhà Bè": "Hồ Chí Minh",
    "Quận 1": "Hồ Chí Minh",
    "Quận 2": "Hồ Chí Minh",
    "Quận 3": "Hồ Chí Minh",
    "Quận 4": "Hồ Chí Minh",
    "Quận 5": "Hồ Chí Minh",
    "Quận 6": "Hồ Chí Minh",
    "Quận 7": "Hồ Chí Minh",
    "Cần Giờ": "Hồ Chí Minh",
    "Quận 8": "Hồ Chí Minh",
    "Quận 9": "Hồ Chí Minh",
    "Quận 10": "Hồ Chí Minh",
    "Quận 11": "Hồ Chí Minh",
    "Quận 12": "Hồ Chí Minh",
    "Hồ Chí Minh": "Hồ Chí Minh",
    "hồ chí minh": "Hồ Chí Minh",
    "HỒ CHÍ MINH": "Hồ Chí Minh",
    "Việc làm Hồ Chí Minh": "Hồ Chí Minh",
    "TPHCM": "Hồ Chí Minh",
    "TP.HCM": "Hồ Chí Minh",
    "TP HCM": "Hồ Chí Minh",
    "TP-HCM": "Hồ Chí Minh",
    "tphcm": "Hồ Chí Minh",
    "HCM": "Hồ Chí Minh",
    "hcm": "Hồ Chí Minh",
    "Nam Trung Bộ": "Nam Trung Bộ",
    "KV Nam Trung Bộ": "Nam Trung Bộ",
    "Bắc Trung Bộ": "Bắc Trung Bộ",
    "KV Bắc Trung Bộ": "Bắc Trung Bộ",
    "Tây Nguyên": "Tây Nguyên",
    "KV Tây Nguyên": "Tây Nguyên",
    "Toàn quốc": "Toàn quốc",
    "toàn quốc": "Toàn quốc",
    "Toàn Quốc": "Toàn quốc",
    "KV Đông Nam Bộ": "Đông Nam Bộ",
    "Bắc Bộ": "Bắc Bộ",
    "Miền Bắc": "Bắc Bộ",
    "Trung Bộ": "Trung Bộ",
    "Miền Trung": "Trung Bộ",
    "Nam Bộ": "Nam Bộ",
    "Miền Nam": "Nam Bộ",
    "Đồng Bằng Sông Cửu Long": "Nam Bộ",
    "Cửu Long": "Nam Bộ",
    "Ba Ria - Vung Tau": "Bà Rịa - Vũng Tàu",
    "Vũng Tàu": "Bà Rịa - Vũng Tàu",
    "Bà Rịa-Vũng Tàu": "Bà Rịa - Vũng Tàu",
    "Nước Ngoài": "Nước Ngoài",
    "Nước ngoài": "Nước Ngoài",
    "Bac Gianh": "Bắc Giang",
    "Bac Kan": "Bắc Kạn",
    "Bac Lieu": "Bạc Liêu",
    "Bac Ninh": "Bắc Ninh",
    "Ben Tre": "Bến Tre",
    "Binh Dinh": "Bình Định",
    "Binh Duong": "Bình Dương",
    "Binh Phuoc": "Bình Phước",
    "Binh Thuan": "Bình Thuận",
    "Ca Mau": "Cà Mau",
    "Cao Bang": "Cao Bằng",
    "Dak Nong": "Đắk Nông",
    "Đắc Nông": "Đắk Nông",
    "Dien Bien": "Điện Biên",
    "Dong Nai": "Đồng Nai",
    "Cẩm Mỹ": "Đồng Nai",
    "Dong Thap": "Đồng Tháp",
    "Ha Giang": "Hà Giang",
    "Ha Nam": "Hà Nam",
    "Ha Tinh": "Hà Tĩnh",
    "Hai Duong": "Hải Dương",
    "Hau Giang": "Hậu Giang",
    "Hoa Binh": "Hòa Bình",
    "Hung Yen": "Hưng Yên",
    "Khanh Hoa": "Khánh Hòa",
    "Khánh Hoà": "Khánh Hòa",
    "TP Nha Trang": "Khánh Hòa",
    "Kien Giang": "Kiên Giang",
    "Lai Chau": "Lai Châu",
    "Lam Dong": "Lâm Đồng",
    "Lang Son": "Lạng Sơn",
    "Nam Dinh": "Nam Định",
    "Nghe An": "Nghệ An",
    "Ninh Binh": "Ninh Bình",
    "Ninh Thuan": "Ninh Thuận",
    "Phu Tho": "Phú Thọ",
    "Quang Binh": "Quảng Bình",
    "Vạn Ninh": "Quảng Bình",
    "Quang Nam": "Quảng Nam",
    "Quang Ngai": "Quảng Ngãi",
    "Quang Ninh": "Quảng Ninh",
    "Quang Tri": "Quảng Trị",
    "Soc Trang": "Sóc Trăng",
    "Son La": "Sơn La",
    "Tay Ninh": "Tây Ninh",
    "Thai Binh": "Thái Bình",
    "Thai Nguyen": "Thái Nguyên",
    "Thanh Hoa": "Thanh Hóa",
    "Thanh Hoá": "Thanh Hóa",
    "Thua Thien Hue": "Thừa Thiên Huế",
    "Thừa Thiên-Huế": "Thừa Thiên Huế",
    "Tien Giang": "Tiền Giang",
    "Tra Vinh": "Trà Vinh",
    "Tuyen Quang": "Tuyên Quang",
    "Vinh Long": "Vĩnh Long",
    "Vinh Phuc": "Vĩnh Phúc",
    "Yen Bai": "Yên Bái",
    "Phu Yen": "Phú Yên",
    "Can Tho": "Cần Thơ",
    "Da Nang": "Đà Nẵng",
    "Hai Phong": "Hải Phòng",
    "Ha Noi": "Hà Nội",
    "Ha Tay": "Hà Nội",
    "Hà Đông": "Hà Nội",
    "Ha Dong": "Hà Nội",
    "Ho Chi Minh": "Hồ Chí Minh",
    "Việc làm TP.HCM": "Hồ Chí Minh",
    "Nam Trung Bo": "Nam Trung Bộ",
    "Bac Trung Bo": "Bắc Trung Bộ",
    "Tay Nguyen": "Tây Nguyên",
    "Khác": "Toàn quốc",
  };
  
  const b = {
    "An Ninh - Bảo Vệ": "An ninh – Bảo vệ",
    "An ninh - Bảo vệ": "An ninh – Bảo vệ",
    "Bảo vệ - An ninh - Vệ sỹ": "An ninh – Bảo vệ",
    "Bảo vệ - Vệ sĩ - An ninh": "An ninh – Bảo vệ",
    "Biên - Phiên dịch": "Biên – Phiên dịch",
    "Biên dịch - Phiên dịch": "Biên – Phiên dịch",
    "Biên phiên dịch": "Biên – Phiên dịch",
    "Biên phiên dịch (tiếng Nhật)": "Biên – Phiên dịch",
    "Biên phiên dịch - Thông dịch viên": "Biên – Phiên dịch",
    "Ngoại ngữ - Biên phiên dịch": "Biên – Phiên dịch",
    "Phiên dịch - Ngoại ngữ": "Biên – Phiên dịch",
    "Ngoại ngữ": "Biên – Phiên dịch",
    "Công chức - Viên chức": "Công chức - Viên chức",
    "Báo chí - Biên tập": "Báo chí – Tuyên truyền",
    "Báo chí - Biên tập viên": "Báo chí – Tuyên truyền",
    "Báo chí - Biên tập viên - Xuất bản": "Báo chí – Tuyên truyền",
    "Báo chí - Truyền hình": "Báo chí – Tuyên truyền",
    "Truyền hình - Báo chí - Biên tập": "Báo chí – Tuyên truyền",
    "Biên tập - Báo chí - Truyền hình": "Báo chí – Tuyên truyền",
    "Bưu chính": "Bưu chính - Giao vận - Kho vận - Vật tư",
    "Bưu chính VT": "Bưu chính - Giao vận - Kho vận - Vật tư",
    "Bưu chính - Viễn thông": "Bưu chính - Giao vận - Kho vận - Vật tư",
    "Bưu chính viễn thông": "Bưu chính - Giao vận - Kho vận - Vật tư",
    "Giao nhận - Vận chuyển - Kho bãi": "Bưu chính - Giao vận - Kho vận - Vật tư",
    "Tài xế - Lái xe - Giao nhận": "Bưu chính - Giao vận - Kho vận - Vật tư",
    "Vận chuyển - Giao nhận": "Bưu chính - Giao vận - Kho vận - Vật tư",
    "Vận chuyển - Giao nhận - Kho vận": "Bưu chính - Giao vận - Kho vận - Vật tư",
    "Vận chuyển - Giao thông - Kho bãi":
      "Bưu chính - Giao vận - Kho vận - Vật tư",
    "Kho vận - Vật tư": "Bưu chính - Giao vận - Kho vận - Vật tư",
    "Kho vận - Vật tư - Thu mua": "Bưu chính - Giao vận - Kho vận - Vật tư",
    "Thu mua - Vật tư": "Bưu chính - Giao vận - Kho vận - Vật tư",
    "Vật tư - Mua hàng": "Bưu chính - Giao vận - Kho vận - Vật tư",
    "Vật tư - Thiết bị - Mua hàng": "Bưu chính - Giao vận - Kho vận - Vật tư",
    "Vận tải": "Bưu chính - Giao vận - Kho vận - Vật tư",
    "Vận tải - Kho vận": "Bưu chính - Giao vận - Kho vận - Vật tư",
    "Vận tải - Lái xe - Tài xế": "Bưu chính - Giao vận - Kho vận - Vật tư",
    "Bảo hiểm": "Bảo hiểm - Chứng khoán",
    "Bảo hiểm - Tư vấn bảo hiểm": "Bảo hiểm - Chứng khoán",
    "Tư vấn bảo hiểm": "Bảo hiểm - Chứng khoán",
    "Chứng khoán": "Bảo hiểm - Chứng khoán",
    "Chứng khoán - Vàng": "Bảo hiểm - Chứng khoán",
    "Chứng khoán - Vàng - Ngoại tệ": "Bảo hiểm - Chứng khoán",
    "KD bất động sản": "Bất động sản",
    "Bất động sản": "Bất động sản",
    "Logistics": "Logistics",
    "CNTT - Phần cứng - Mạng": "CNTT - Phần cứng / Mạng",
    "IT Phần cứng - Mạng": "CNTT - Phần cứng / Mạng",
    "IT phần cứng - mạng": "CNTT - Phần cứng / Mạng",
    "CNTT - Phần mềm": "CNTT - Phần mềm",
    "CNTT - Tin học": "CNTT - Phần mềm",
    "IT phần mềm": "CNTT - Phần mềm",
    "Công nghệ thông tin": "CNTT - Phần mềm",
    "Công nghiệp": "Công nghiệp",
    "Công nghệ cao": "Công nghệ cao",
    "Freelance": "Freelance",
    "Công nghệ Ô tô": "Cơ khí – Chế tạo – Tự động hoá – Kỹ thuật ứng dụng",
    "Cơ khí - Chế tạo": "Cơ khí – Chế tạo – Tự động hoá – Kỹ thuật ứng dụng",
    "Cơ khí - Chế tạo - Tự động hóa":
      "Cơ khí – Chế tạo – Tự động hoá – Kỹ thuật ứng dụng",
    "Cơ khí - Chế tạo máy": "Cơ khí – Chế tạo – Tự động hoá – Kỹ thuật ứng dụng",
    "Cơ khí - Kĩ thuật ứng dụng":
      "Cơ khí – Chế tạo – Tự động hoá – Kỹ thuật ứng dụng",
    "Cơ khí - Ô tô - Tự động hóa":
      "Cơ khí – Chế tạo – Tự động hoá – Kỹ thuật ứng dụng",
    "Kỹ thuật ứng dụng - Cơ khí":
      "Cơ khí – Chế tạo – Tự động hoá – Kỹ thuật ứng dụng",
    "Kỹ thuật ứng dụng": "Cơ khí – Chế tạo – Tự động hoá – Kỹ thuật ứng dụng",
    "Ô tô": "Cơ khí – Chế tạo – Tự động hoá – Kỹ thuật ứng dụng",
    "Ô tô - Xe máy": "Cơ khí – Chế tạo – Tự động hoá – Kỹ thuật ứng dụng",
    "Ôtô - Xe máy": "Cơ khí – Chế tạo – Tự động hoá – Kỹ thuật ứng dụng",
    "Khoáng sản": "Dầu khí – Hóa chất – Khoáng sản",
    "Dầu khí": "Dầu khí – Hóa chất – Khoáng sản",
    "Dầu khí - Hóa chất": "Dầu khí – Hóa chất – Khoáng sản",
    "Dầu khí - Khoáng sản": "Dầu khí – Hóa chất – Khoáng sản",
    "Địa chất - Khoáng sản": "Dầu khí – Hóa chất – Khoáng sản",
    "Dầu khí - Địa chất": "Dầu khí – Hóa chất – Khoáng sản",
    "Dệt may": "Dệt may - Da giày - Thời Trang",
    "Dệt may - Da giày": "Dệt may - Da giày - Thời Trang",
    "Dệt may - Da giày - Thời trang": "Dệt may - Da giày - Thời Trang",
    "Giày da - Thuộc da": "Dệt may - Da giày - Thời Trang",
    "Thời trang": "Dệt may - Da giày - Thời Trang",
    "Thời trang - Nghệ thuật": "Dệt may - Da giày - Thời Trang",
    "Dịch vụ": "Dịch vụ - Khách sạn - Nhà hàng - Du lịch",
    "Dịch vụ khách hàng": "Dịch vụ - Khách sạn - Nhà hàng - Du lịch",
    "Du lịch": "Dịch vụ - Khách sạn - Nhà hàng - Du lịch",
    "Du lịch - Khách sạn": "Dịch vụ - Khách sạn - Nhà hàng - Du lịch",
    "Du lịch - Nhà hàng - Khách sạn": "Dịch vụ - Khách sạn - Nhà hàng - Du lịch",
    "Khách sạn - Du lịch": "Dịch vụ - Khách sạn - Nhà hàng - Du lịch",
    "Khách sạn - Nhà hàng": "Dịch vụ - Khách sạn - Nhà hàng - Du lịch",
    "Nhà hàng - Dịch vụ ăn uống": "Dịch vụ - Khách sạn - Nhà hàng - Du lịch",
    "Nhà hàng - Khách sạn": "Dịch vụ - Khách sạn - Nhà hàng - Du lịch",
    "Giao thông - Vận tải - Thủy lợi - Cầu đường":
      "Giao thông vận tải – Thủy lợi - Cầu đường",
    "Giao thông - Vận tải - Thủy lợi - Cầu đườ...":
      "Giao thông vận tải – Thủy lợi - Cầu đường",
    "Giao thông vận tải": "Giao thông vận tải – Thủy lợi - Cầu đường",
    "Thủy lợi": "Giao thông vận tải – Thủy lợi - Cầu đường",
    "Người giúp việc": "Giúp việc - Phục vụ",
    "Người giúp việc - Phục vụ - Tạp vụ": "Giúp việc - Phục vụ",
    "Phục vụ - Tạp vụ - Giúp việc": "Giúp việc - Phục vụ",
    "NV trông quán Internet": "Giúp việc - Phục vụ",
    "Nhân viên trông quán internet": "Giúp việc - Phục vụ",
    "Giải trí": "Giải trí",
    "Giải trí - Vui chơi": "Giải trí",
    "Nghệ thuật - Thiết kế - Giải trí": "Giải trí",
    "Game": "Giải trí",
    "Games": "Giải trí",
    "Thể dục - Thể thao": "Giải trí",
    "Hoạch định - Dự án": "Hoạch định dự án",
    "Hàng hải": "Hàng hải",
    "Hàng không": "Hàng không",
    "An toàn lao động": "An toàn lao động",
    "Hành chính - Thư ký": "Hành chính - Văn phòng",
    "Hành chính - Thư ký - Trợ lý": "Hành chính - Văn phòng",
    "Hành chính - Văn phòng": "Hành chính - Văn phòng",
    "Thư ký - Hành chánh": "Hành chính - Văn phòng",
    "Thư ký - Trợ lý": "Hành chính - Văn phòng",
    "Hóa học": "Hóa học – Sinh học",
    "Hóa học - Sinh học": "Hóa học – Sinh học",
    "Hoá học - Sinh học": "Hóa học – Sinh học",
    "Công nghệ sinh học": "Hóa học – Sinh học",
    "Dược phẩm - Công nghệ sinh học": "Hóa học – Sinh học",
    "Hoá chất - Sinh học": "Hóa học – Sinh học",
    "Dược - Hóa chất - Sinh hóa": "Hóa học – Sinh học",
    "Dược - Sinh học": "Hóa học – Sinh học",
    "Hóa chất - Sinh hóa - Thực phẩm": "Hóa học – Sinh học",
    "Sinh viên - Mới tốt nghiệp - Thực tập":
      "Sinh viên - Mới tốt nghiệp - Thực tập",
    "Thực tập": "Sinh viên - Mới tốt nghiệp - Thực tập",
    "In ấn - Xuất bản": "In ấn – xuất bản",
    "Xuất bản - In ấn": "In ấn – xuất bản",
    "Khoa học tự nhiên": "Khoa học tự nhiên",
    "Ngoại thương - XNK": "Kinh doanh quốc tế",
    "Ngoại thương - Xuất nhập khẩu": "Kinh doanh quốc tế",
    "Xuất - Nhập khẩu": "Kinh doanh quốc tế",
    "Xuất - Nhập khẩu - Ngoại thương": "Kinh doanh quốc tế",
    "Xuất nhập khẩu": "Kinh doanh quốc tế",
    "Xuất nhập khẩu - Ngoại thương": "Kinh doanh quốc tế",
    "Kiến trúc": "Kiến trúc – Thiết kế nội thất",
    "Kiến trúc - Nội thất": "Kiến trúc – Thiết kế nội thất",
    "Kiến trúc - TK nội thất": "Kiến trúc – Thiết kế nội thất",
    "Kiến trúc - Thiết kế nội thất": "Kiến trúc – Thiết kế nội thất",
    "Nội ngoại thất": "Kiến trúc – Thiết kế nội thất",
    "Nội thất - Ngoại thất": "Kiến trúc – Thiết kế nội thất",
    "Trang trí nội thất": "Kiến trúc – Thiết kế nội thất",
    "Đồ Gỗ": "Kiến trúc – Thiết kế nội thất",
    "Đồ gỗ": "Kiến trúc – Thiết kế nội thất",
    "Thiết kế nội thất": "Kiến trúc – Thiết kế nội thất",
    "Tài chính - Kế toán - Kiểm toán": "Kế toán - Kiểm toán",
    "Kế toán - Kiểm toán": "Kế toán - Kiểm toán",
    "Kỹ thuật": "Kỹ thuật",
    "Luật - Pháp lý": "Luật",
    "Pháp luật - Pháp lý": "Luật",
    "Pháp lý - Luật": "Luật",
    "Marketing - PR": "Marketing - Tiếp thị - Quảng cáo",
    "Marketing - Tư vấn": "Marketing - Tiếp thị - Quảng cáo",
    "Quảng cáo - Marketing - PR": "Marketing - Tiếp thị - Quảng cáo",
    "Tiếp thị - Marketing": "Marketing - Tiếp thị - Quảng cáo",
    "Tiếp thị": "Marketing - Tiếp thị - Quảng cáo",
    "Tiếp thị - Quảng cáo": "Marketing - Tiếp thị - Quảng cáo",
    "Tiếp thị trực tuyến": "Marketing - Tiếp thị - Quảng cáo",
    "Quảng cáo - Khuyến mãi": "Marketing - Tiếp thị - Quảng cáo",
    "Marketing - Truyền thông - Quảng cáo": "Marketing - Tiếp thị - Quảng cáo",
    "Quảng cáo - Khuyến mãi - Đối ngoại": "Marketing - Tiếp thị - Quảng cáo",
    "Quảng cáo - Đối ngoại - Truyền Thông": "Marketing - Tiếp thị - Quảng cáo",
    "PG - PB - Lễ tân": "Marketing - Tiếp thị - Quảng cáo",
    "Promotion Girl (PG)": "Marketing - Tiếp thị - Quảng cáo",
    "Promotion Girl - Boy (PG - PB)": "Marketing - Tiếp thị - Quảng cáo",
    "Nghiên cứu thị trường": "Marketing - Tiếp thị - Quảng cáo",
    "Phát triển thị trường": "Marketing - Tiếp thị - Quảng cáo",
    "Môi trường": "Môi trường – Xử lý chất thải",
    "Môi trường - Xử lý chất thải": "Môi trường – Xử lý chất thải",
    "Nghệ thuật - Điện ảnh": "Nghệ thuật – Điện ảnh",
    "Mỹ thuật - Nghệ thuật - Điện ảnh": "Nghệ thuật – Điện ảnh",
    "Nhân sự": "Nhân sự",
    "Quản lý điều hành": "Nhân sự",
    "Bảo trì - Sửa chữa": "Nhân viên Bảo trì - Sửa chữa",
    "Bảo trì - Sữa chữa": "Nhân viên Bảo trì - Sửa chữa",
    "Hàng cao cấp": "Nhân viên kinh doanh - Bán hàng - Tư  vấn - CSKH",
    "Hàng tiêu dùng": "Nhân viên kinh doanh - Bán hàng - Tư  vấn - CSKH",
    "Bán hàng kỹ thuật": "Nhân viên kinh doanh - Bán hàng - Tư  vấn - CSKH",
    "Nhân viên kinh doanh": "Nhân viên kinh doanh - Bán hàng - Tư  vấn - CSKH",
    "Bán hàng": "Nhân viên kinh doanh - Bán hàng - Tư  vấn - CSKH",
    "Bán hàng - Kinh doanh": "Nhân viên kinh doanh - Bán hàng - Tư  vấn - CSKH",
    "Bán lẻ - Bán sỉ": "Nhân viên kinh doanh - Bán hàng - Tư  vấn - CSKH",
    "Bán lẻ - bán sỉ": "Nhân viên kinh doanh - Bán hàng - Tư  vấn - CSKH",
    "Kinh doanh": "Nhân viên kinh doanh - Bán hàng - Tư  vấn - CSKH",
    "Kinh doanh - Bán hàng": "Nhân viên kinh doanh - Bán hàng - Tư  vấn - CSKH",
    "Tư vấn": "Nhân viên kinh doanh - Bán hàng - Tư  vấn - CSKH",
    "Tư vấn - Chăm sóc khách hàng":
      "Nhân viên kinh doanh - Bán hàng - Tư  vấn - CSKH",
    "Chăm sóc khách hàng": "Nhân viên kinh doanh - Bán hàng - Tư  vấn - CSKH",
    "Hàng gia dụng": "Nhân viên kinh doanh - Bán hàng - Tư  vấn - CSKH",
    "Hàng gia dụng - Chăm sóc cá nhân":
      "Nhân viên kinh doanh - Bán hàng - Tư  vấn - CSKH",
    "Thời vụ - Bán thời gian": "Thời vụ - Bán thời gian",
    "Làm bán thời gian": "Thời vụ - Bán thời gian",
    "Sinh viên làm thêm": "Sinh viên làm thêm",
    "Startup": "Startup",
    "Lương cao": "Lương cao",
    "Việc làm cấp cao": "Lương cao",
    "Việc làm Tết": "Việc làm Tết",
    "Nông - Lâm - Ngư nghiệp": "Nông - Lâm - Ngư nghiệp",
    "Nông lâm": "Nông - Lâm - Ngư nghiệp",
    "Nông nghiệp": "Nông - Lâm - Ngư nghiệp",
    "Nông nghiệp - Lâm nghiệp": "Nông - Lâm - Ngư nghiệp",
    "Lâm Nghiệp": "Nông - Lâm - Ngư nghiệp",
    "Thủy sản - Hải sản": "Nông - Lâm - Ngư nghiệp",
    "Thuỷ Hải Sản": "Nông - Lâm - Ngư nghiệp",
    "Chăn nuôi - Thú y": "Nông - Lâm - Ngư nghiệp",
    "Phi chính phủ - Phi lợi nhuận": "Phi chính phủ - Phi lợi nhuận",
    "NGO - Phi chính phủ - Phi lợi nhuận": "Phi chính phủ - Phi lợi nhuận",
    "Quan hệ đối ngoại": "Quan hệ đối ngoại",
    "Quan hệ cộng đồng": "Quan hệ đối ngoại",
    "Đối ngoại": "Quan hệ đối ngoại",
    "Lao động phổ thông": "Lao động phổ thông",
    "Xuất khẩu lao động": "Quan hệ đối ngoại",
    "Quản lý chất lượng": "Quản lý chất lượng (QA / QC)",
    "Quản lý chất lượng (QA - QC)": "Quản lý chất lượng (QA / QC)",
    "Thẩm định - Giám định - Quản lý chất lượng": "Quản lý chất lượng (QA / QC)",
    "Thẩm định - Giám định - Quản lý chất lư...": "Quản lý chất lượng (QA / QC)",
    "QA - QC - Thẩm định - Giám định": "Quản lý chất lượng (QA / QC)",
    "Quản trị kinh doanh": "Quản trị kinh doanh",
    "Kinh tế": "Quản trị kinh doanh",
    "Spa - Làm đẹp": "Spa - Mỹ phẩm - Trang sức",
    "Làm đẹp - Thể lực - Spa": "Spa - Mỹ phẩm - Trang sức",
    "Spa - Mỹ phẩm - Trang sức": "Spa - Mỹ phẩm - Trang sức",
    "Mỹ phẩm": "Spa - Mỹ phẩm - Trang sức",
    "Mỹ phẩm - Thời trang - Trang sức": "Spa - Mỹ phẩm - Trang sức",
    "Mỹ phẩm - Trang sức": "Spa - Mỹ phẩm - Trang sức",
    "Giáo dục - Đào tạo": "Sư phạm",
    "Giáo dục - Đào tạo - Thư viện": "Sư phạm",
    "Thư viện": "Sư phạm",
    "Sản xuất": "Sản xuất - Vận hành sản xuất",
    "Sản xuất - Vận hành sản xuất": "Sản xuất - Vận hành sản xuất",
    "Khu chế xuất - Khu công nghiệp": "Sản xuất - Vận hành sản xuất",
    "Mỹ thuật - Hội hoạ": "Thiết kế - Mỹ thuật",
    "Mỹ thuật - Nghệ thuật - Thiết kế": "Thiết kế - Mỹ thuật",
    "Thiết kế - Mỹ thuật": "Thiết kế - Mỹ thuật",
    "Thiết kế - Tạo mẫu": "Thiết kế - Mỹ thuật",
    "Thiết kế đồ hoạ web": "Thiết kế đồ họa web",
    "Thiết kế đồ họa - Web": "Thiết kế đồ họa web",
    "Thiết kế đồ họa": "Thiết kế đồ họa web",
    "Thương mại điện tử": "Thương mại điện tử",
    "Thủ công mỹ nghệ": "Thủ công mỹ nghệ",
    "Thực phẩm & Đồ uống": "Thực phẩm – Đồ uống",
    "Thực phẩm - DV ăn uống": "Thực phẩm – Đồ uống",
    "Thực phẩm - Đồ uống": "Thực phẩm – Đồ uống",
    "Công nghệ thực phẩm - Dinh dưỡng": "Thực phẩm – Đồ uống",
    "Sản phẩm công nghiệp": "Trang thiết bị gia dụng - Công nghiệp - Văn phòng",
    "Trang thiết bị công nghiệp":
      "Trang thiết bị gia dụng - Công nghiệp - Văn phòng",
    "Trang thiết bị gia dụng":
      "Trang thiết bị gia dụng - Công nghiệp - Văn phòng",
    "Trang thiết bị văn phòng":
      "Trang thiết bị gia dụng - Công nghiệp - Văn phòng",
    "Tài chính - Đầu tư": "Tài chính - Ngân hàng",
    "Ngân hàng": "Tài chính - Ngân hàng",
    "Ngân hàng - Chứng khoán": "Tài chính - Ngân hàng",
    "Ngân hàng - Chứng khoán - Đầu tư": "Tài chính - Ngân hàng",
    "Ngân hàng - Tài Chính": "Tài chính - Ngân hàng",
    "Ngân hàng - Tài chính": "Tài chính - Ngân hàng",
    "Đầu tư": "Tài chính - Ngân hàng",
    "Tổ chức sự kiện": "Tổ chức sự kiện - Quà tặng",
    "Tổ chức sự kiện - Quà tặng": "Tổ chức sự kiện - Quà tặng",
    "Xây dựng": "Xây dựng",
    "Y tế - Dược": "Y tế - Dược",
    "Y tế - Dược phẩm": "Y tế - Dược",
    "Y tế - Chăm sóc sức khỏe": "Y tế - Dược",
    "Y tế": "Y tế - Dược",
    "Chăm sóc sức khỏe - Y tế": "Y tế - Dược",
    "Dược phẩm": "Y tế - Dược",
    "Viễn Thông": "Điện tử viễn thông",
    "Điện tử viễn thông": "Điện tử viễn thông",
    "Điện - Điện tử": "Điện – Điện tử - Điện lạnh",
    "Điện - Điện tử - Điện lạnh": "Điện – Điện tử - Điện lạnh",
    "Điện - điện công nghiệp": "Điện – Điện tử - Điện lạnh",
    "Điện lạnh - Nhiệt lạnh": "Điện – Điện tử - Điện lạnh",
    "Điện tử": "Điện – Điện tử - Điện lạnh",
    "Khác": "Khác",
    "Ngành nghề khác": "Khác",
  };
  
  export const workPlaces = Object.values(a);
  export const majors = Object.values(b);